name: library_example
description: "Example of creating libraries"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  method_channel_example:
    path: packages/method_channel_example
  event_channel_example:
    path: packages/event_channel_example
  basic_message_channel_example:
    path: packages/basic_message_channel_example
  pigeon_example:
    path: packages/pigeon_example
  run_engine_example:
    path: packages/run_engine_example
  federated_plugin:
    path: packages/federated_plugin/federated_plugin
  shared_part_builder_example:
    path: packages/shared_part_builder_example
  part_builder_example:
    path: packages/part_builder_example
  library_builder_example:
    path: packages/library_builder_example

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  source_gen: ^2.0.0

flutter:
  uses-material-design: true
